name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t my-flask-app .
      

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker tag my-flask-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
      

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes.yaml
      continue-on-error: true
